/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import common.CommonMethod;
import common.HibernateUtil;
import entities.EntityComponent;
import entities.TaiKhoan;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import service.dao.ServiceDAOFactory;

/**
 *
 * @author KenyDinh
 */
public class Login extends ParentGui {

    /**
     * Creates new form DangNhap
     */
    public Login() {
        initComponents();
        this.setLocation(CommonMethod.getWidth(this.getWidth()), CommonMethod.getHeight(this.getHeight()));
        ImageIcon icon = CommonMethod.getImageIcon("login");
        if (icon != null) {
            setIconImage(icon.getImage());
        }
        tendangnhap.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_panel = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        formdangnhap = new javax.swing.JPanel();
        lb_tendangnhap = new javax.swing.JLabel();
        tendangnhap = new javax.swing.JTextField();
        lb_matkhau = new javax.swing.JLabel();
        btn_dangnhap = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        matkhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        title_panel.setBackground(new java.awt.Color(0, 102, 0));

        lb_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Đăng Nhập Hệ Thống");

        javax.swing.GroupLayout title_panelLayout = new javax.swing.GroupLayout(title_panel);
        title_panel.setLayout(title_panelLayout);
        title_panelLayout.setHorizontalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        title_panelLayout.setVerticalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        formdangnhap.setBackground(new java.awt.Color(0, 102, 0));

        lb_tendangnhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_tendangnhap.setForeground(new java.awt.Color(255, 255, 255));
        lb_tendangnhap.setText("Tên đăng nhập:");

        tendangnhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tendangnhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tendangnhapKeyPressed(evt);
            }
        });

        lb_matkhau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb_matkhau.setForeground(new java.awt.Color(255, 255, 255));
        lb_matkhau.setText("Mật khẩu:");

        btn_dangnhap.setBackground(new java.awt.Color(255, 255, 255));
        btn_dangnhap.setText("Đăng Nhập");
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });

        error.setForeground(new java.awt.Color(255, 255, 255));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        matkhau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        matkhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matkhauKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout formdangnhapLayout = new javax.swing.GroupLayout(formdangnhap);
        formdangnhap.setLayout(formdangnhapLayout);
        formdangnhapLayout.setHorizontalGroup(
            formdangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(formdangnhapLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(formdangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_matkhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formdangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tendangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(matkhau))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formdangnhapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_dangnhap)
                .addGap(152, 152, 152))
        );
        formdangnhapLayout.setVerticalGroup(
            formdangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formdangnhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formdangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formdangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dangnhap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formdangnhapLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lb_tendangnhap, tendangnhap});

        formdangnhapLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lb_matkhau, matkhau});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formdangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(formdangnhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        dangnhap();
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void matkhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matkhauKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            dangnhap();
        }
    }//GEN-LAST:event_matkhauKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closeForm();
    }//GEN-LAST:event_formWindowClosing

    private void tendangnhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tendangnhapKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            matkhau.requestFocus();
        }
    }//GEN-LAST:event_tendangnhapKeyPressed

    private void dangnhap(){
        String username = tendangnhap.getText();
        char[] p = matkhau.getPassword();
        if(username == null || username.trim().isEmpty()){
            error.setText("Tên đăng nhập không hợp lệ!");
            return;
        }
        if(p == null || p.length == 0){
            error.setText("Mật khẩu không hợp lệ!");
            return;
        }
        String password = new String(p);
        TaiKhoan tk = new TaiKhoan();
        tk.setUsername(username);
        tk.setPassword(CommonMethod.encryptedPasswordMD5(password));
        EntityComponent entity = ServiceDAOFactory.select(tk);
        if(null == entity){
            error.setText("Tên đăng nhập hoặc mật khẩu không đúng!");
        }else{
            tk = (TaiKhoan)entity;
            Home home = Home.getInstance(true);
            home.setTaiKhoan(tk);
            home.setVisible(true);
            this.dispose();
        }
    }
    
    private void closeForm(){
        HibernateUtil.closeSessionFactory();
        System.exit(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JLabel error;
    private javax.swing.JPanel formdangnhap;
    private javax.swing.JLabel lb_matkhau;
    private javax.swing.JLabel lb_tendangnhap;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPasswordField matkhau;
    private javax.swing.JTextField tendangnhap;
    private javax.swing.JPanel title_panel;
    // End of variables declaration//GEN-END:variables
}
