/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.elem;

import common.CommonMethod;
import entities.DonVi;
import entities.EntityComponent;
import entities.HangHoa;
import entities.LoaiHangHoa;
import gui.ElementGui;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import service.dao.ServiceDAOFactory;

/**
 *
 * @author KenyDinh
 */
public class HangHoaFrame extends ElementGui {

    private List<DonVi> listDonvi = new ArrayList<DonVi>();
    private List<LoaiHangHoa> listLoaiHangHoa = new ArrayList<LoaiHangHoa>();

    /**
     * Creates new form HangHoaFrame
     */
    public HangHoaFrame() {
        initComponents();
        initLocation();
        initCombobox();
        ImageIcon icon = CommonMethod.getImageIcon("vatlieu_1");
        if (icon != null) {
            setIconImage(icon.getImage());
        }
    }

    private void initCombobox() {
        List<EntityComponent> list_dv = ServiceDAOFactory.selectList(new DonVi());
        List<EntityComponent> list_lhh = ServiceDAOFactory.selectList(new LoaiHangHoa());
        DefaultComboBoxModel<String> donviModel = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> loaihanghoaModel = new DefaultComboBoxModel<>();
        boolean b = true;
        for (EntityComponent e : list_dv) {
            DonVi dv = (DonVi) e;
            listDonvi.add(dv);
            donviModel.addElement(dv.getMadonvi());
            if (b) {
                tf_tendonvi.setText(dv.getTendonvi());
                b = false;
            }
        }
        b = true;
        for (EntityComponent e : list_lhh) {
            LoaiHangHoa lhh = (LoaiHangHoa) e;
            listLoaiHangHoa.add(lhh);
            loaihanghoaModel.addElement(lhh.getMaloaihanghoa());
            if (b) {
                tf_tenloaihanghoa.setText(lhh.getTenloaihanghoa());
                b = false;
            }
        }
        cbb_madonvi.setModel(donviModel);
        cbb_maloaihanghoa.setModel(loaihanghoaModel);
        updateDonVi();
        updateLoaiHangHoa();
    }

    @Override
    public void initData(EntityComponent entity) {
        if (entity != null && entity instanceof HangHoa) {
            HangHoa hh = (HangHoa) entity;
            tf_mahanghoa.setText(hh.getMahanghoa());
            tf_mahanghoa.setEditable(false);
            tf_gia.setValue(hh.getGia());
            cbb_madonvi.setSelectedItem(hh.getMadonvi());
            cbb_maloaihanghoa.setSelectedItem(hh.getMaloaihanghoa());
            for (DonVi dv : listDonvi) {
                if (dv.getMadonvi().equals(hh.getMadonvi())) {
                    tf_tendonvi.setText(dv.getTendonvi());
                    break;
                }
            }
            for (LoaiHangHoa lhh : listLoaiHangHoa) {
                if (lhh.getTenloaihanghoa().equals(hh.getMahanghoa())) {
                    tf_tenloaihanghoa.setText(lhh.getTenloaihanghoa());
                    break;
                }
            }
            tf_tenhanghoa.setText(hh.getTenhanghoa());
            lb_title.setText("Cập Nhật Vật Liệu");
            btn_ok.setText("Cập Nhập");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_mahanghoa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_tenhanghoa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbb_madonvi = new javax.swing.JComboBox();
        tf_tendonvi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_gia = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        cbb_maloaihanghoa = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tf_tenloaihanghoa = new javax.swing.JTextField();
        lb_mess = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quản Lý Vật Liệu");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        lb_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Thêm Vật Liệu Mới");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã vật liệu:");

        tf_mahanghoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên vật liệu:");

        tf_tenhanghoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mã đơn vị:");

        cbb_madonvi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbb_madonvi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_madonviItemStateChanged(evt);
            }
        });

        tf_tendonvi.setEditable(false);
        tf_tendonvi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tên đơn vị:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giá:");

        tf_gia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_gia.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã loại vật liệu:");

        cbb_maloaihanghoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbb_maloaihanghoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_maloaihanghoaItemStateChanged(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên loại vật liệu:");

        tf_tenloaihanghoa.setEditable(false);
        tf_tenloaihanghoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lb_mess.setForeground(new java.awt.Color(255, 255, 255));
        lb_mess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_ok.setBackground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("Thêm Mới");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_mess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbb_maloaihanghoa, 0, 81, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbb_madonvi, 0, 100, Short.MAX_VALUE)
                                    .addComponent(tf_mahanghoa))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tf_tendonvi, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tf_tenhanghoa)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_tenloaihanghoa)))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_mahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tf_tenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbb_madonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf_tendonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tf_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbb_maloaihanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tf_tenloaihanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lb_mess, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btn_ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        okButton();
    }//GEN-LAST:event_btn_okActionPerformed

    private void cbb_madonviItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_madonviItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            updateDonVi();
        }
    }//GEN-LAST:event_cbb_madonviItemStateChanged

    private void cbb_maloaihanghoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_maloaihanghoaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            updateLoaiHangHoa();
        }
    }//GEN-LAST:event_cbb_maloaihanghoaItemStateChanged

    private void okButton() {
        lb_mess.setText("");
        String mahanghoa = tf_mahanghoa.getText();
        String tenhanghoa = tf_tenhanghoa.getText();
        int gia = Integer.valueOf(tf_gia.getValue().toString());
        if (cbb_madonvi.getSelectedItem() == null) {
            lb_mess.setText("Mã đơn vị không được bỏ trống!");
            return;
        }
        if (cbb_maloaihanghoa.getSelectedItem() == null) {
            lb_mess.setText("Mã loại vật liệu không được bỏ trống!");
            return;
        }
        if (mahanghoa == null || mahanghoa.trim().isEmpty()) {
            lb_mess.setText("Mã vật liệu không được bỏ trống!");
            return;
        }
        if (tenhanghoa == null || tenhanghoa.trim().isEmpty()) {
            lb_mess.setText("Tên vật liệu không được bỏ trống!");
            return;
        }
        if (tf_mahanghoa.isEditable()) {
            HangHoa temp = new HangHoa();
            temp.setMahanghoa(mahanghoa.trim());
            if (ServiceDAOFactory.select(temp) != null) {
                lb_mess.setText("Mã Vật Liệu đã tồn tại!");
                return;
            }
        }
        HangHoa hh = new HangHoa();
        hh.setMahanghoa(mahanghoa.trim());
        hh.setTenhanghoa(tenhanghoa.trim());
        hh.setMadonvi(cbb_madonvi.getSelectedItem().toString());
        hh.setGia(gia);
        hh.setMaloaihanghoa(cbb_maloaihanghoa.getSelectedItem().toString());
        if (!ServiceDAOFactory.insertOrUpdate(hh)) {
            if (tf_mahanghoa.isEditable()) {
                lb_mess.setText("Lỗi:Không thêm được vật liệu mới!");
            } else {
                lb_mess.setText("Lỗi:Không cập nhất được thông tin vật liệu!");
            }
            return;
        }
        okCloseFrame(new HangHoa());
    }

    private void updateDonVi() {
        if (cbb_madonvi.getSelectedItem() == null) {
            return;
        }
        String madonvi = cbb_madonvi.getSelectedItem().toString();
        for (DonVi dv : listDonvi) {
            if (dv.getMadonvi().equals(madonvi)) {
                tf_tendonvi.setText(dv.getTendonvi());
                break;
            }
        }
    }

    private void updateLoaiHangHoa() {
        if (cbb_maloaihanghoa.getSelectedItem() == null) {
            return;
        }
        String maloaihanghoa = cbb_maloaihanghoa.getSelectedItem().toString();
        for (LoaiHangHoa lhh : listLoaiHangHoa) {
            if (lhh.getMaloaihanghoa().equals(maloaihanghoa)) {
                tf_tenloaihanghoa.setText(lhh.getTenloaihanghoa());
                break;
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox cbb_madonvi;
    private javax.swing.JComboBox cbb_maloaihanghoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_mess;
    private javax.swing.JLabel lb_title;
    private javax.swing.JSpinner tf_gia;
    private javax.swing.JTextField tf_mahanghoa;
    private javax.swing.JTextField tf_tendonvi;
    private javax.swing.JTextField tf_tenhanghoa;
    private javax.swing.JTextField tf_tenloaihanghoa;
    // End of variables declaration//GEN-END:variables
}
