/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.elem;

import common.CommonDefine;
import common.CommonMethod;
import entities.ChucVu;
import entities.EntityComponent;
import entities.TaiKhoan;
import enums.Role;
import gui.ElementGui;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import service.dao.ServiceDAOFactory;

/**
 *
 * @author KenyDinh
 */
public class TaiKhoanFrame extends ElementGui {

    private List<ChucVu> listChucVus;
    private List<Role> listRoles;
    private String matkhau;
    private final String MK = "password";

    /**
     * Creates new form HangHoaFrame
     */
    public TaiKhoanFrame() {
        initComponents();
        initLocation();
        ImageIcon icon = CommonMethod.getImageIcon("taikhoan_1");
        if (icon != null) {
            setIconImage(icon.getImage());
        }
        initConfig();
        pn_id.setVisible(false);
    }

    private void initConfig() {
        listChucVus = new ArrayList<>();
        listRoles = new ArrayList<>();
        DefaultComboBoxModel<String> chucvuModel = new DefaultComboBoxModel<>();
        DefaultComboBoxModel<String> roleModel = new DefaultComboBoxModel<>();
        ChucVu cv = new ChucVu();
        List<EntityComponent> list = ServiceDAOFactory.selectList(cv);
        for (EntityComponent e : list) {
            ChucVu c = (ChucVu) e;
            listChucVus.add(c);
            chucvuModel.addElement(c.getTenchucvu());
        }
        for (Role role : Role.values()) {
            listRoles.add(role);
            roleModel.addElement(role.getName());
        }
        cbb_chucvu.setModel(chucvuModel);
        cbb_role.setModel(roleModel);
    }

    @Override
    public void initData(EntityComponent entity) {
        if (entity != null && entity instanceof TaiKhoan) {
            TaiKhoan tk = (TaiKhoan) entity;
            lb_title.setText("Cập Nhật Thông Tin Người Dùng");
            btn_ok.setText("Cập Nhập");
            pn_id.setVisible(true);
            tf_id.setText(String.valueOf(tk.getId()));
            tf_tendangnhap.setText(tk.getUsername());
            tf_tendangnhap.setEditable(false);
            tf_pass.setVisible(false);
            lb_pass.setVisible(false);
            matkhau = tk.getPassword();
            tf_diachi.setText(tk.getDiachi());
            tf_email.setText(tk.getEmail());
            tf_sdt.setText(tk.getSodienthoai());
            for (ChucVu cv : listChucVus) {
                if (cv.getMachucvu().equals(tk.getMachucvu())) {
                    cbb_chucvu.setSelectedItem(cv.getTenchucvu());
                    break;
                }
            }
            for (Role role : listRoles) {
                if (role.getId() == tk.getRole()) {
                    cbb_role.setSelectedItem(role.getName());
                    break;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_tendangnhap = new javax.swing.JTextField();
        lb_pass = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        pn_id = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_sdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbb_role = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbb_chucvu = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_diachi = new javax.swing.JTextArea();
        lb_mess = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quản Lý Người Dùng");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        lb_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Thêm Người Dùng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên đăng nhập:");

        tf_tendangnhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lb_pass.setForeground(new java.awt.Color(255, 255, 255));
        lb_pass.setText("Mật khẩu:");

        btn_ok.setBackground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("Thêm Mới");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");

        tf_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pn_id.setBackground(new java.awt.Color(0, 102, 0));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Id:");

        tf_id.setEditable(false);
        tf_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout pn_idLayout = new javax.swing.GroupLayout(pn_id);
        pn_id.setLayout(pn_idLayout);
        pn_idLayout.setHorizontalGroup(
            pn_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_idLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pn_idLayout.setVerticalGroup(
            pn_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số điện thoại:");

        tf_sdt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Role:");

        cbb_role.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chức vụ:");

        cbb_chucvu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Địa chỉ:");

        tf_diachi.setColumns(20);
        tf_diachi.setLineWrap(true);
        tf_diachi.setRows(3);
        tf_diachi.setTabSize(4);
        tf_diachi.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tf_diachi);

        lb_mess.setForeground(new java.awt.Color(255, 255, 255));
        lb_mess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tf_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_mess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lb_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_pass))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbb_role, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbb_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(pn_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tendangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pass)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_chucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_mess, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btn_ok)
                .addGap(10, 10, 10))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel3, lb_pass});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        okButton();
    }//GEN-LAST:event_btn_okActionPerformed

    private void okButton() {
        lb_mess.setText("");
        String tendangnhap = tf_tendangnhap.getText();
        char[] pass = tf_pass.getPassword();
        String email = tf_email.getText();
        String diachi = tf_diachi.getText();
        String sodienthoai = tf_sdt.getText();

        if (tendangnhap == null || tendangnhap.trim().isEmpty()) {
            lb_mess.setText("Tên đăng nhập không được bỏ trống!");
            return;
        }
        if (tendangnhap.trim().equals("root")) {
            lb_mess.setText("Tên đăng nhập không hợp lệ!");
            return;
        }
        if (diachi == null || diachi.trim().isEmpty()) {
            lb_mess.setText("Địa chỉ không được bỏ trống!");
            return;
        }
        if (sodienthoai == null || sodienthoai.trim().isEmpty()) {
            lb_mess.setText("Số điện thoại không được bỏ trống!");
            return;
        }
        if (!pn_id.isVisible()) {
            if (pass == null || pass.length == 0) {
                lb_mess.setText("Mật khẩu không được bỏ trống!");
                return;
            }
            matkhau = CommonMethod.encryptedPasswordMD5(new String(pass));
        }
        if(matkhau == null){
            matkhau = CommonMethod.encryptedPasswordMD5(new String("1"));
        }
        if (email == null) {
            email = "";
        }
        String machucvu = null;
        int role = Role.DEFAULT_ROLE.getId();
        if (listChucVus != null && cbb_chucvu.getSelectedIndex() >= 0 && cbb_chucvu.getSelectedIndex() < listChucVus.size()) {
            machucvu = listChucVus.get(cbb_chucvu.getSelectedIndex()).getMachucvu();
        }
        if (listRoles != null && cbb_role.getSelectedIndex() >= 0 && cbb_role.getSelectedIndex() < listRoles.size()) {
            role = listRoles.get(cbb_role.getSelectedIndex()).getId();
        }
        if (machucvu == null) {
            lb_mess.setText("Chức vụ không hợp lệ!");
            return;
        }
        TaiKhoan tk = new TaiKhoan();
        if (pn_id.isVisible()) {
            String strId = tf_id.getText();
            if (strId == null || strId.trim().isEmpty()) {
                lb_mess.setText("Id tài khoản không hợp lệ!");
                return;
            }
            tk.setId(CommonMethod.stringToInt(strId));
        } else {
            TaiKhoan temp = new TaiKhoan();
            temp.setSelectQuery("FROM " + CommonDefine.TAIKHOAN + " WHERE username='" + tendangnhap + "'");
            if (!ServiceDAOFactory.executeQueryList(temp).isEmpty()) {
                lb_mess.setText("Tài khoản đã tồn tại!");
                return;
            }
        }
        tk.setDiachi(diachi);
        tk.setEmail(email);
        tk.setMachucvu(machucvu);
        tk.setPassword(matkhau);
        tk.setRole(role);
        tk.setSodienthoai(sodienthoai);
        tk.setUsername(tendangnhap);
        if (!ServiceDAOFactory.insertOrUpdate(tk)) {
            if (pn_id.isVisible()) {
                lb_mess.setText("Lỗi:Cập nhật thông tin thất bại!");
            } else {
                lb_mess.setText("Lỗi:Thêm thông tin thất bại!");
            }
            return;
        }
        okCloseFrame();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox cbb_chucvu;
    private javax.swing.JComboBox cbb_role;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_mess;
    private javax.swing.JLabel lb_pass;
    private javax.swing.JLabel lb_title;
    private javax.swing.JPanel pn_id;
    private javax.swing.JTextArea tf_diachi;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_id;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_tendangnhap;
    // End of variables declaration//GEN-END:variables
}
