/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.elem;

import common.CommonDefine;
import common.CommonMethod;
import entities.CongTrinh;
import entities.DonVi;
import entities.EntityComponent;
import entities.HangHoa;
import entities.History;
import entities.VatLieuTonKho;
import entities.VatLieuXuat;
import enums.Action;
import enums.HistoryType;
import gui.ElementGui;
import gui.Home;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import service.dao.ServiceDAOFactory;

/**
 *
 * @author KenyDinh
 */
public class VatLieuXuatFrame extends ElementGui {

    private VatLieuXuat vatlieuxuat;
    private List<HangHoa> listHangHoa;
    private List<DonVi> listDonVi;
    private boolean isUpdate;

    /**
     * Creates new form HangHoaFrame
     */
    public VatLieuXuatFrame() {
        initComponents();
        initLocation();
        initConfig();
        ImageIcon icon = CommonMethod.getImageIcon("vatlieuxuat_1");
        if(icon != null){
            setIconImage(icon.getImage());
        }
    }

    private void initConfig() {
        listHangHoa = new ArrayList<>();
        listDonVi = new ArrayList<>();
        SimpleDateFormat sdf = new SimpleDateFormat(CommonDefine.DATE_FORMAT_GUI);
        date_ngayxuat.setFormats(sdf);
        List<EntityComponent> listHH = ServiceDAOFactory.selectList(new HangHoa());
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (EntityComponent e : listHH) {
            HangHoa h = (HangHoa) e;
            model.addElement(h.getMahanghoa());
            listHangHoa.add(h);
        }
        List<EntityComponent> listDV = ServiceDAOFactory.selectList(new DonVi());
        for (EntityComponent e : listDV) {
            DonVi dv = (DonVi) e;
            listDonVi.add(dv);
        }
        cbb_mahanghoa.setModel(model);
        updateInfoHangHoa();
        onUpdateMHH();
    }

    @Override
    public void initData(EntityComponent entity) {
        if (entity != null && entity instanceof VatLieuXuat) {
            VatLieuXuat vlx = (VatLieuXuat) entity;
            isUpdate = true;
            lb_title.setText("Cập Nhật Thông Tin Vật Liệu");
            btn_ok.setText("Cập Nhật");
            date_ngayxuat.setDate(CommonMethod.getDateStringDB(vlx.getNgayxuat()));
            tf_khoiluong.setValue(vlx.getKhoiluong());
            CongTrinh c = new CongTrinh();
            c.setMacongtrinh(vlx.getMacongtrinh());
            EntityComponent e1 = ServiceDAOFactory.select(c);
            if (e1 == null) {
                lb_mess.setText("Không tìm thấy Công Trình!");
                return;
            }
            CongTrinh ct = (CongTrinh) e1;
            tf_macongtrinh.setText(ct.getMacongtrinh());
            tf_tencongtrinh.setText(ct.getTencongtrinh());
            HangHoa h = new HangHoa();
            h.setMahanghoa(vlx.getMahanghoa());
            EntityComponent e2 = ServiceDAOFactory.select(h);
            if (e2 == null) {
                lb_mess.setText("Không tìm thấy Vật Liệu!");
                return;
            }
            HangHoa hh = (HangHoa) e2;
            tf_tenhanghoa.setText(hh.getTenhanghoa());
            cbb_mahanghoa.setSelectedItem(hh.getMahanghoa());
            tf_tonggiatri.setValue(vlx.getKhoiluong() * hh.getGia());
            DonVi d = new DonVi();
            d.setMadonvi(hh.getMadonvi());
            EntityComponent e3 = ServiceDAOFactory.select(d);
            if (e3 == null) {
                lb_mess.setText("Không tìm thất Đơn Vị Vật Liệu!");
                return;
            }
            DonVi dv = (DonVi) e3;
            tf_tendonvi.setText(dv.getMadonvi());
            this.vatlieuxuat = vlx;
        } else if (entity != null && entity instanceof CongTrinh) {
            CongTrinh ct = (CongTrinh) entity;
            tf_macongtrinh.setText(ct.getMacongtrinh());
            tf_tencongtrinh.setText(ct.getTencongtrinh());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_macongtrinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_mess = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_tencongtrinh = new javax.swing.JTextArea();
        tf_tenhanghoa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        date_ngayxuat = new org.jdesktop.swingx.JXDatePicker();
        cbb_mahanghoa = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_tendonvi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_khoiluong = new javax.swing.JSpinner();
        tf_tonggiatri = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Quản Lý Xuất Vật Liệu");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        lb_title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Thông Tin Vật Liệu Xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã công trình:");

        tf_macongtrinh.setEditable(false);
        tf_macongtrinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên công trình:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ngày xuất:");

        lb_mess.setForeground(new java.awt.Color(255, 255, 255));
        lb_mess.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_ok.setBackground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("Thêm ");
        btn_ok.setToolTipText("");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        tf_tencongtrinh.setEditable(false);
        tf_tencongtrinh.setColumns(20);
        tf_tencongtrinh.setLineWrap(true);
        tf_tencongtrinh.setRows(3);
        tf_tencongtrinh.setTabSize(4);
        tf_tencongtrinh.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tf_tencongtrinh);

        tf_tenhanghoa.setEditable(false);
        tf_tenhanghoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã vật liệu:");

        date_ngayxuat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbb_mahanghoa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbb_mahanghoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_mahanghoaItemStateChanged(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên vật liệu:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Đơn vị:");

        tf_tendonvi.setEditable(false);
        tf_tendonvi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Khối lượng:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tổng giá trị:");

        tf_khoiluong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_khoiluong.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        tf_khoiluong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tf_khoiluongStateChanged(evt);
            }
        });

        tf_tonggiatri.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tf_tonggiatri.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        tf_tonggiatri.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbb_mahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_khoiluong)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(tf_tenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_tendonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_tonggiatri))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_mess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_macongtrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date_ngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_macongtrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(date_ngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_tenhanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_mahanghoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(tf_tendonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tf_khoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tonggiatri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(lb_mess, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btn_ok)
                .addGap(10, 10, 10))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        okButton();
    }//GEN-LAST:event_btn_okActionPerformed

    private void cbb_mahanghoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_mahanghoaItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            updateInfoHangHoa();
        }
    }//GEN-LAST:event_cbb_mahanghoaItemStateChanged

    private void tf_khoiluongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tf_khoiluongStateChanged
        onUpdateMHH();
    }//GEN-LAST:event_tf_khoiluongStateChanged

    private void updateInfoHangHoa() {
        if(cbb_mahanghoa.getSelectedItem() == null) return;
        for (HangHoa hh : listHangHoa) {
            if (hh.getMahanghoa().equals(cbb_mahanghoa.getSelectedItem().toString())) {
                for (DonVi dv : listDonVi) {
                    if (dv.getMadonvi().equals(hh.getMadonvi())) {
                        tf_tendonvi.setText(dv.getTendonvi());
                        tf_tenhanghoa.setText(hh.getTenhanghoa());
                        tf_tonggiatri.setValue(hh.getGia() * CommonMethod.stringToInt(tf_khoiluong.getValue().toString()));
                        break;
                    }
                }
                break;
            }
        }
    }

    private void okButton() {
        lb_mess.setText("");
        if (!isUpdate || vatlieuxuat == null) {
            vatlieuxuat = new VatLieuXuat();
        }
        Date ngayxuat = date_ngayxuat.getDate();
        String macongtrinh = tf_macongtrinh.getText();
        int khoiluong = CommonMethod.stringToInt(tf_khoiluong.getValue().toString());
        if (cbb_mahanghoa.getSelectedItem() == null) {
            lb_mess.setText("Mã vật liệu không được bỏ trống!");
            return;
        }
        String mahanghoa = cbb_mahanghoa.getSelectedItem().toString();
        if (ngayxuat == null) {
            lb_mess.setText("Ngày xuất không được bỏ trống!");
            return;
        }
        if (macongtrinh == null || macongtrinh.trim().isEmpty()) {
            lb_mess.setText("Mã công trình không được bỏ trống!");
            return;
        }
        //
        if (isUpdate) {
            if (vatlieuxuat.getMahanghoa().equals(mahanghoa) && vatlieuxuat.getNgayxuat().equals(CommonMethod.getFormatDateStringDB(ngayxuat)) && vatlieuxuat.getKhoiluong() == khoiluong) {
                okCloseFrame();
                return;
            }
        }
        //
        History history = new History();
        history.setDatemodify(CommonMethod.getFormatDateStringDB(new Date()));
        if (isUpdate) {
            history.setAction(Action.UPDATE.getName());
            history.setDateold(vatlieuxuat.getNgayxuat());
            history.setKhoiluongcu(vatlieuxuat.getKhoiluong());
            history.setMahanghoacu(vatlieuxuat.getMahanghoa());
        } else {
            history.setAction(Action.INSERT.getName());
        }
        //
        VatLieuTonKho vltk = new VatLieuTonKho();
        int klt = 0;
        if (isUpdate) {
            vltk.setMacongtrinh(vatlieuxuat.getMacongtrinh());
            vltk.setMahanghoa(vatlieuxuat.getMahanghoa());
            EntityComponent e0 = ServiceDAOFactory.select(vltk);
            if (e0 != null) {
                klt = ((VatLieuTonKho) e0).getKhoiluongton();
                vltk.setKhoiluongton(klt + vatlieuxuat.getKhoiluong());
                if (!ServiceDAOFactory.insertOrUpdate(vltk)) {
                    CommonMethod.writeLog(Home.tennguoidung, "[ServiceDAOFactory.insertOrUpdate]");
                }
            }
        }
        //
        vatlieuxuat.setNgayxuat(CommonMethod.getFormatDateStringDB(ngayxuat));
        vatlieuxuat.setMacongtrinh(macongtrinh.trim());
        vatlieuxuat.setKhoiluong(khoiluong);
        vatlieuxuat.setManguoixuat(Home.tennguoidung);
        vatlieuxuat.setMahanghoa(mahanghoa);
        //
        vltk = new VatLieuTonKho();
        klt = 0;
        vltk.setMacongtrinh(vatlieuxuat.getMacongtrinh());
        vltk.setMahanghoa(vatlieuxuat.getMahanghoa());
        EntityComponent e0 = ServiceDAOFactory.select(vltk);
        if (e0 != null) {
            klt = ((VatLieuTonKho) e0).getKhoiluongton();
        }
        vltk.setKhoiluongton(klt - vatlieuxuat.getKhoiluong());
        if (!ServiceDAOFactory.insertOrUpdate(vltk)) {
            CommonMethod.writeLog(Home.tennguoidung, "[ServiceDAOFactory.insertOrUpdate]");
        }
        //
        history.setDatenew(vatlieuxuat.getNgayxuat());
        history.setKhoiluongmoi(vatlieuxuat.getKhoiluong());
        history.setMahanghoamoi(vatlieuxuat.getMahanghoa());
        history.setMacongtrinh(vatlieuxuat.getMacongtrinh());
        history.setType(HistoryType.OUT.getName());
        history.setTennguoidung(Home.tennguoidung);
        //
        if (!ServiceDAOFactory.insertOrUpdate(vatlieuxuat)) {
            if (isUpdate) {
                lb_mess.setText("Lỗi:Cập nhật thông tin thất bại!");
            } else {
                lb_mess.setText("Lỗi:Thêm thông tin thất bại!");
            }
            return;
        }
        //
        if (!ServiceDAOFactory.insertOrUpdate(history)) {
            CommonMethod.writeLog(Home.tennguoidung, "[ServiceDAOFactory.insertOrUpdate]");
        }
        //
        VatLieuXuat nvlx = new VatLieuXuat();
        nvlx.setMacongtrinh(vatlieuxuat.getMacongtrinh());
        okCloseFrame(nvlx);
    }

    private void onUpdateMHH() {
        if(cbb_mahanghoa.getSelectedItem() == null) return;
        for (HangHoa hh : listHangHoa) {
            if (hh.getMahanghoa().equals(cbb_mahanghoa.getSelectedItem().toString())) {
                tf_tonggiatri.setValue(hh.getGia() * CommonMethod.stringToInt(tf_khoiluong.getValue().toString()));
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JComboBox cbb_mahanghoa;
    private org.jdesktop.swingx.JXDatePicker date_ngayxuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_mess;
    private javax.swing.JLabel lb_title;
    private javax.swing.JSpinner tf_khoiluong;
    private javax.swing.JTextField tf_macongtrinh;
    private javax.swing.JTextArea tf_tencongtrinh;
    private javax.swing.JTextField tf_tendonvi;
    private javax.swing.JTextField tf_tenhanghoa;
    private javax.swing.JSpinner tf_tonggiatri;
    // End of variables declaration//GEN-END:variables
}
